on:
  push:
    tags: ["v[0-9].[0-9]+.[0-9]+"]  # Trigger on version tags
    branches:
      - "main"  # Trigger on pushes to the main branch
      - "development"
      - "staging"

jobs:
  build-artifact:
    name: build
    runs-on: ubuntu-latest
    outputs:
      version_fingerprint: ${{ steps.hcp.outputs.version_fingerprint }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Packer
        uses: hashicorp/setup-packer@v3.1.0
        id: setup

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Adjust as necessary

      - name: Packer Init
        run: packer init .

      - name: Packer Build - Branches
        if: startswith(github.ref, 'refs/heads/')
        run: packer build .

      - name: Packer Build - Tags
        if: startswith(github.ref, 'refs/tags/v')
        run: packer build .

      - name: Get HCP Packer version fingerprint from packer manifest
        id: hcp
        run: |
          last_run_uuid=$(jq -r '.last_run_uuid' "./packer_manifest.json")
          build=$(jq -r '.builds[] | select(.packer_run_uuid == "'"$last_run_uuid"'")' "./packer_manifest.json")
          version_fingerprint=$(echo "$build" | jq -r '.custom_data.version_fingerprint')
          echo "::set-output name=version_fingerprint::$version_fingerprint"
